Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -31,7 +31,7 @@ jobs:
     steps:
       # Runs a set of commands using the runners shell
       - name: success
-        run: exit 0
+        run: exit 1
   
   should-check:
     if: always()
@@ -47,5 +47,5 @@ jobs:
           (needs.shouldnt-fail.result != 'success' || 
           needs.should-succeed.result != 'success')
         run: |
-          echo "Should've not been run"
+          echo "Should fail, if one of previous jobs fail and succeeds otherwise"
           exit 1
