Update nrc.yml

diff --git a/.github/workflows/nrc.yml b/.github/workflows/nrc.yml
--- a/.github/workflows/nrc.yml
+++ b/.github/workflows/nrc.yml
@@ -7,9 +7,8 @@ env:
   GH_TOKEN: ${{ github.token }}
   gh_repo: duckdb/duckdb
 jobs:
-  first:
+  linux:
     runs-on: ubuntu-latest
-    continue-on-error: true
     steps:
       - name: Check LinuxRelease
         run: |
@@ -22,13 +21,13 @@ jobs:
             gh run list --repo ${{ env.gh_repo }} --event repository_dispatch --workflow LinuxRelease --created $(date +%Y-%m-%d) --json databaseId > run_id.csv
             run_id=$(tail -n 1 run_id.csv | awk -F "[:}]" '{ print $2 }' | tr -d ' "')
             gh run download $run_id --repo ${{ env.gh_repo }}
-            unzip duckdb-binaries-linux/duckdb_cli-linux-amd64.zip || { echo "Unzip failed"; exit 1; }
+            unzip duckdb-binaries-linux/duckdb_cli*.zip || { echo "Unzip failed"; exit 1; }
             # verify versions
             ./duckdb --version > pragma_version.csv
             short_sha=$(tail -n 2 pragma_version.csv | awk '{ print $2 }')
             full_sha=$(gh run view $run_id --repo duckdb/duckdb --json headSha -q .headSha)
             if [[ $full_sha != $short_sha* ]]; then
-              printf "\`\`\`\nThe version of duckdb_cli-linux-amd64 build ($p_version) is not the same as the version triggered the build ($sha).\n\`\`\`" > issue_body.txt
+              printf "\`\`\`\nThe version of Linux build ($p_version) is not the same as the version triggered the build ($sha).\n\`\`\`" > issue_body.txt
             else
               # try to load extension
               ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='spatial';" > sp.csv
@@ -49,5 +48,44 @@ jobs:
               fi
             fi
           fi
-      - name: Setup upterm session
-        uses: lhotari/action-upterm@v1
+  osx:
+    runs-on: macos-latest
+    steps:
+      - name: Check OSX
+        run: | 
+          conclusion=$(gh run list --repo ${{ env.gh_repo }} --event repository_dispatch --workflow OSX --created $(date +%Y-%m-%d) --json conclusion) 
+          if echo $conclusion | grep -q 'failure'; then
+            gh run list --repo ${{ env.gh_repo }} --event repository_dispatch --workflow OSX --created $(date +%Y-%m-%d) --json url > url.csv
+            url=$(tail -n 1 url.csv | awk -F "[:}]" '{ print $3 }')
+            printf "\`\`\`\nThe nightly-build OSX had failed.\n Please see the run https:$url.\n\`\`\`" > issue_body.txt
+          else
+            gh run list --repo ${{ env.gh_repo }} --event repository_dispatch --workflow OSX --created $(date +%Y-%m-%d) --json databaseId > run_id.csv
+            run_id=$(tail -n 1 run_id.csv | awk -F "[:}]" '{ print $2 }' | tr -d ' "')
+            gh run download $run_id --repo ${{ env.gh_repo }}
+            unzip duckdb-binaries-osx/duckdb_cli*.zip || { echo "Unzip failed"; exit 1; }
+            # verify versions
+            ./duckdb --version > pragma_version.csv
+            short_sha=$(tail -n 2 pragma_version.csv | awk '{ print $2 }')
+            full_sha=$(gh run view $run_id --repo duckdb/duckdb --json headSha -q .headSha)
+            if [[ $full_sha != $short_sha* ]]; then
+              printf "\`\`\`\nThe version of OSX build ($p_version) is not the same as the version triggered the build ($sha).\n\`\`\`" >> issue_body.txt
+            else
+              # try to load extension
+              ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='spatial';" > sp.csv
+              sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
+              if [[ $sp == 'false' ]]; then
+                ./duckdb -c "INSTALL spatial;"
+                ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='spatial';" > sp.csv
+                sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
+                if [[ $sp != 'true' ]]; then
+                  echo "Failed to INSTALL an extension." >> issue_body.txt
+                fi
+                if ! ./duckdb -c "LOAD spatial;" ; then
+                  echo "Failed to LOAD an extension." >> issue_body.txt
+                fi
+                if ./duckdb -c "INSTALL unexpected;"; then
+                  echo "INSTALLation of unexpected extension didn't return 1." >> issue_body.txt
+                fi
+              fi
+            fi
+          fi
