Update nrc.yml

diff --git a/.github/workflows/nrc.yml b/.github/workflows/nrc.yml
--- a/.github/workflows/nrc.yml
+++ b/.github/workflows/nrc.yml
@@ -14,6 +14,9 @@ on:
       runs-on:
         required: true
         type: string
+      extension:
+        required: false
+        type: string
 env:
   GH_TOKEN: ${{ github.token }}
 jobs:
@@ -28,7 +31,7 @@ jobs:
           if echo $conclusion | grep -q 'failure'; then
             gh run list --repo duckdb/duckdb --event repository_dispatch --workflow ${{ inputs.nightly-build }} --created $(date +%Y-%m-%d) --json url > url.csv
             url=$(tail -n 1 url.csv | awk -F "[:}]" '{ print $3 }')
-            printf "\`\`\`\nThe nightly-build ${{ inputs.nightly-build }} had failed.\n Please see the run https:$url.\n\`\`\`" > issue_body.txt
+            printf "The nightly-build \`${{ inputs.nightly-build }}\` had failed: https:$url.\n " > issue_body.txt
           else
             gh run list --repo duckdb/duckdb --event repository_dispatch --workflow ${{ inputs.nightly-build }} --created $(date +%Y-%m-%d) --json databaseId > run_id.csv
             run_id=$(tail -n 1 run_id.csv | awk -F "[:}]" '{ print $2 }' | tr -d ' "')
@@ -39,28 +42,28 @@ jobs:
             short_sha=$(tail -n 2 pragma_version.csv | awk '{ print $2 }')
             full_sha=$(gh run view $run_id --repo duckdb/duckdb --json headSha -q .headSha)
             if [[ $full_sha != $short_sha* ]]; then
-              printf "\`\`\`\nThe version of Linux build ($p_version) is not the same as the version triggered the build ($sha).\n\`\`\`" > issue_body.txt
+              printf "The version of \`${{ input.nightly-build }}\` build (\`$short_sha\`) is not the same as the version triggered the build (\`$full_sha\`).\n " > issue_body.txt
             else
-              ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='spatial';"
-              ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='spatial';" > sp.csv
+              ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ input.extension }}';"
+              ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ input.extension }}';" > sp.csv
               sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
               if [[ $sp == 'false' ]]; then
                 echo try to INSTALL extension
-                ./duckdb -c "INSTALL spatial;"
-                ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='spatial';"
-                ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='spatial';" > sp.csv
+                ./duckdb -c "INSTALL ${{ input.extension }};"
+                ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ input.extension }}';"
+                ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ input.extension }}';" > sp.csv
                 sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
                 if [[ $sp != 'true' ]]; then
                   echo "Failed to INSTALL an extension." >> issue_body.txt
                 fi
                 echo try to load extension
-                if ./duckdb -c "LOAD spatial;" ; then
+                if ./duckdb -c "LOAD ${{ input.extension }};" ; then
                   echo "Failed to LOAD an extension." >> issue_body.txt
                 fi
-                echo install unexpected
-                if ! ./duckdb -c "INSTALL unexpected;"; then
-                  echo "INSTALLation of unexpected extension didn't return 1." >> issue_body.txt
-                fi
+                # echo install unexpected
+                # if ! ./duckdb -c "INSTALL unexpected;"; then
+                #   echo "INSTALLation of unexpected extension didn't return 1." >> issue_body.txt
+                # fi
               fi
             fi
           fi
