try less

diff --git a/.github/workflows/nrc_copy.yml b/.github/workflows/nrc_copy.yml
--- a/.github/workflows/nrc_copy.yml
+++ b/.github/workflows/nrc_copy.yml
@@ -109,19 +109,19 @@ jobs:
                 ./duckdb --version > pragma_version.csv
                 short_sha=\$(tail -n 2 pragma_version.csv | awk '{ print \$2 }')
                 echo \$short_sha
-                echo \$full_sha
-                echo Build version matches to the version triggered the nightly-build workflow
-                if [[ \$full_sha != \$short_sha* ]]; then
-                  printf '- The version of \`\${{ inputs.nightly-build }}\` build (\`\$short_sha\`) doesn't match to the version triggered the build (\`\$full_sha\`).\n' > issue_body_${{ inputs.architecture }}.txt
-                  cat issue_body_${{ inputs.architecture }}.txt
-                  exit 1
-                else  
-                  echo Downloading duckdb-binaries-${{ inputs.platform }} artifact is failed.
-                  printf '#### No artifacts with name duckdb-binaries-${{ inputs.platform }} provided.\n' > issue_body_${{ inputs.architecture }}.txt
-                  # echo 'has_artifact=false' >> $GITHUB_OUTPUT
-                  echo 'has_artifact=false' > /duckdb/has_artifact.txt
-                  echo \$has_artifact
-                fi
+                # echo \$full_sha
+                # echo Build version matches to the version triggered the nightly-build workflow
+                # if [[ \$full_sha != \$short_sha* ]]; then
+                #   printf '- The version of \`\${{ inputs.nightly-build }}\` build (\`\$short_sha\`) doesn't match to the version triggered the build (\`\$full_sha\`).\n' > issue_body_${{ inputs.architecture }}.txt
+                #   cat issue_body_${{ inputs.architecture }}.txt
+                #   exit 1
+                # else  
+                #   echo Downloading duckdb-binaries-${{ inputs.platform }} artifact is failed.
+                #   printf '#### No artifacts with name duckdb-binaries-${{ inputs.platform }} provided.\n' > issue_body_${{ inputs.architecture }}.txt
+                #   # echo 'has_artifact=false' >> $GITHUB_OUTPUT
+                #   echo 'has_artifact=false' > /duckdb/has_artifact.txt
+                #   echo \$has_artifact
+                # fi
               "
             fi
             has_artifact=$(cat ./has_artifact.txt)
