see if it finds duckdb

diff --git a/.github/workflows/nrc_copy.yml b/.github/workflows/nrc_copy.yml
--- a/.github/workflows/nrc_copy.yml
+++ b/.github/workflows/nrc_copy.yml
@@ -105,24 +105,24 @@ jobs:
             if [[  ${{ inputs.architecture }} == 'linux-aarch64' ]]; then
               echo ${{ inputs.architecture }}
               docker run --rm --platform linux/arm64 -v $(pwd):/duckdb -e full_sha=$full_sha ubuntu:22.04 /bin/bash "
-                echo 'has_artifact=true' > /duckdb/has_artifact.txt
-                echo \$full_sha 🐠
+                # echo 'has_artifact=true' > /duckdb/has_artifact.txt
+                # echo \$full_sha 🐠
                 cd duckdb
                 ./duckdb --version
-                ./duckdb --version > pragma_version.csv
-                short_sha=\$(tail -n 2 pragma_version.csv | awk '{ print \$2 }')
-                echo \$short_sha
-                echo Build version matches to the version triggered the nightly-build workflow
-                if [[ \$full_sha != \$short_sha* ]]; then
-                  printf '- The version of \`\${{ inputs.nightly-build }}\` build (\`\$short_sha\`) doesn't match to the version triggered the build (\`\$full_sha\`).\n' > issue_body_${{ inputs.architecture }}.txt
-                  cat issue_body_${{ inputs.architecture }}.txt
-                  exit 1
-                else  
-                  echo Downloading duckdb-binaries-${{ inputs.platform }} artifact is failed.
-                  printf '#### No artifacts with name duckdb-binaries-${{ inputs.platform }} provided.\n' > issue_body_${{ inputs.architecture }}.txt
-                  # echo 'has_artifact=false' >> $GITHUB_OUTPUT
-                  echo 'has_artifact=false' > /duckdb/has_artifact.txt
-                  echo \$has_artifact
+                # ./duckdb --version > pragma_version.csv
+                # short_sha=\$(tail -n 2 pragma_version.csv | awk '{ print \$2 }')
+                # echo \$short_sha
+                # echo Build version matches to the version triggered the nightly-build workflow
+                # if [[ \$full_sha != \$short_sha* ]]; then
+                #   printf '- The version of \`\${{ inputs.nightly-build }}\` build (\`\$short_sha\`) doesn't match to the version triggered the build (\`\$full_sha\`).\n' > issue_body_${{ inputs.architecture }}.txt
+                #   cat issue_body_${{ inputs.architecture }}.txt
+                #   exit 1
+                # else  
+                #   echo Downloading duckdb-binaries-${{ inputs.platform }} artifact is failed.
+                #   printf '#### No artifacts with name duckdb-binaries-${{ inputs.platform }} provided.\n' > issue_body_${{ inputs.architecture }}.txt
+                #   # echo 'has_artifact=false' >> $GITHUB_OUTPUT
+                #   echo 'has_artifact=false' > /duckdb/has_artifact.txt
+                #   echo \$has_artifact
                 "
               fi
             fi
