.github/workflows/tests_nbc_copy.yml

diff --git a/.github/workflows/tests_nbc_copy.yml b/.github/workflows/tests_nbc_copy.yml
--- a/.github/workflows/tests_nbc_copy.yml
+++ b/.github/workflows/tests_nbc_copy.yml
@@ -76,6 +76,7 @@ jobs:
 
       - name: Test ${{ inputs.nightly-build }}
         shell: bash
+        if: inputs.architecture == 'linux-aarch64'
         run: |
           unzip duckdb_cli-${{ inputs.architecture }}.zip
           if [[ ${{ inputs.nightly-build }} == Windows ]]; then
@@ -84,47 +85,58 @@ jobs:
             duckdb=./duckdb
           fi
 
-          if [[ ${{ inputs.architecture == 'linux-aarch64' }} ]]; then
-            docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c 'cd /duckdb; ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > sp.csv
-          else
-            $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';"
-            $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';" > sp.csv
-          fi
+          docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c 'cd /duckdb; ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > sp.csv
           cat sp.csv
 
           sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
           if [[ $sp == 'false' ]]; then
             echo Installing ${{ matrix.extensions }} extension...
-            if [[ ${{ inputs.architecture }} != 'linux-aarch64' ]]; then
-              if ! $duckdb -c "INSTALL ${{ inputs.extension }};"; then
-                echo Failed to install ${{ inputs.extension }} extension.
-                echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ inputs.extension }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-                echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-                exit 1
-              fi
-              echo Loading ${{ inputs.extension }} extension...
-              if ! $duckdb -c "LOAD ${{ inputs.extension }};"; then
-                echo Failed to load ${{ inputs.extension }} extension.
-                echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ inputs.extension }}\`." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-                echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-                exit 1
-              fi
-            else
-              if ! docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "INSTALL $ext;"'; then 
-                echo Failed to install ${{ matrix.extensions }} extension.
-                echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ matrix.extensions }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-                echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-                exit 1
-              fi
-              echo Loading ${{ matrix.extensions }} extension...
-              if ! docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "LOAD $ext;"'; then
-                echo Failed to load ${{ matrix.extensions }} extension.
-                echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ matrix.extensions }}\`." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-                echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-                exit 1
-              fi
+            if ! docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "INSTALL $ext;"'; then 
+              echo Failed to install ${{ matrix.extensions }} extension.
+              echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ matrix.extensions }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
+              echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
+              exit 1
+            fi
+            echo Loading ${{ matrix.extensions }} extension...
+            if ! docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "LOAD $ext;"'; then
+              echo Failed to load ${{ matrix.extensions }} extension.
+              echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ matrix.extensions }}\`." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
+              echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
+              exit 1
             fi
           fi
+
+      - name: Test ${{ inputs.nightly-build }}
+        shell: bash
+        if: inputs.architecture == 'linux-arm64'
+        run: |
+          unzip duckdb_cli-${{ inputs.architecture }}.zip
+          if [[ ${{ inputs.nightly-build }} == Windows ]]; then
+            duckdb=./duckdb.exe
+          else
+            duckdb=./duckdb
+          fi
+          $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';"
+          $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';" > sp.csv
+          cat sp.csv
+          sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
+          if [[ $sp == 'false' ]]; then
+            echo Installing ${{ matrix.extensions }} extension...
+            if ! $duckdb -c "INSTALL ${{ inputs.extension }};"; then
+              echo Failed to install ${{ inputs.extension }} extension.
+              echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ inputs.extension }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              exit 1
+            fi
+            echo Loading ${{ inputs.extension }} extension...
+            if ! $duckdb -c "LOAD ${{ inputs.extension }};"; then
+              echo Failed to load ${{ inputs.extension }} extension.
+              echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ inputs.extension }}\`." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              exit 1
+            fi
+          fi
+      
       
       # - name: Setup upterm session
       #   uses: owenthereal/action-upterm@v1
