.github/workflows/tests_nbc_copy.yml

diff --git a/.github/workflows/tests_nbc_copy.yml b/.github/workflows/tests_nbc_copy.yml
--- a/.github/workflows/tests_nbc_copy.yml
+++ b/.github/workflows/tests_nbc_copy.yml
@@ -73,6 +73,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: duckdb_cli-${{ inputs.architecture }}
+
       - name: Test ${{ inputs.nightly-build }}
         shell: bash
         run: |
@@ -83,21 +84,32 @@ jobs:
             duckdb=./duckdb
           fi
 
-          docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c 'cd /duckdb; ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > sp.csv
+          if [[ ${{ inputs.architecture == 'linux-aarch64' }} ]]; then
+            docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c 'cd /duckdb; ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > sp.csv
+          else
+            $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';"
+            $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';" > sp.csv
+          fi
           cat sp.csv
 
-          # $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';"
-          # $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';" > sp.csv
           sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
           if [[ $sp == 'false' ]]; then
             echo Installing ${{ matrix.extensions }} extension...
+            if [[ ${{ inputs.architecture == 'linux-aarch64' }} ]]; then
+              if ! docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "INSTALL $ext;"'; then 
+                echo Failed to install ${{ matrix.extensions }} extension.
+                echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ matrix.extensions }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
+                echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
+                exit 1
+            else
+              $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';"
+              $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';" > sp.csv
+            fi
+            
             if docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "INSTALL $ext;"'; then 
               echo ${{ matrix.extensions }} extension is installed.
             else
-              echo Failed to install ${{ matrix.extensions }} extension.
-              echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ matrix.extensions }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-              echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-              exit 1
+              
             fi
             echo Loading ${{ matrix.extensions }} extension...
             if docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "LOAD $ext;"'; then
