switch back to one-shot containers

diff --git a/.github/workflows/tests_nbc_copy.yml b/.github/workflows/tests_nbc_copy.yml
--- a/.github/workflows/tests_nbc_copy.yml
+++ b/.github/workflows/tests_nbc_copy.yml
@@ -20,38 +20,38 @@ on:
 env:
   GH_TOKEN: ${{ github.token }}
 jobs:
-  get-matrix:
-    runs-on: ubuntu-latest
-    outputs:
-      extensions: ${{ steps.ex.outputs.extensions }}
-    steps:
-      - name: Checkout the repo with the script
-        uses: actions/checkout@v4
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.10'
-      - uses: actions/checkout@v4
-        with:
-          repository: duckdb/duckdb
-          sparse-checkout: |
-            .github/config
-          path: ext
-      - name: save to GITHUB_OUTPUT
-        id: ex
-        shell: bash
-        run: |
-            chmod +x scripts/find_extensions.py
-            matches=$(python scripts/find_extensions.py ext/.github/config/out_of_tree_extensions.cmake)
-              echo "extensions=$matches" >> $GITHUB_OUTPUT
+  # get-matrix:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     extensions: ${{ steps.ex.outputs.extensions }}
+  #   steps:
+  #     - name: Checkout the repo with the script
+  #       uses: actions/checkout@v4
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.10'
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         repository: duckdb/duckdb
+  #         sparse-checkout: |
+  #           .github/config
+  #         path: ext
+  #     - name: save to GITHUB_OUTPUT
+  #       id: ex
+  #       shell: bash
+  #       run: |
+  #           chmod +x scripts/find_extensions.py
+  #           matches=$(python scripts/find_extensions.py ext/.github/config/out_of_tree_extensions.cmake)
+  #             echo "extensions=$matches" >> $GITHUB_OUTPUT
 
   check-build:
     runs-on: ${{ inputs.runs-on }}
     continue-on-error: true
-    needs: get-matrix
-    strategy:
-      matrix:
-        extensions: ${{ fromJSON(needs.get-matrix.outputs.extensions) }}
+    # needs: get-matrix
+    # strategy:
+    #   matrix:
+    #     extensions: ${{ fromJSON(needs.get-matrix.outputs.extensions) }}
     steps:
       - name: Set up QEMU
         if: ${{ inputs.architecture == 'linux-aarch64' }}
@@ -88,26 +88,32 @@ jobs:
             duckdb=./duckdb
           fi
 
-          docker run --name con --platform linux/aarch64 -v $(pwd)/duckdb:/duckdb -e ext=${{ matrix.extensions }} -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > sp.csv
-          cat sp.csv
+          chmod +x scripts/find_extensions.py
+            matches=$(python scripts/find_extensions.py ext/.github/config/out_of_tree_extensions.cmake)
+              echo "extensions=$matches" >> $GITHUB_OUTPUT
+          
+          foe ext in extensions; do
+            docker run --rm --platform linux/aarch64 -v $(pwd)/duckdb:/duckdb -e ext=$ext -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > sp.csv
+            cat sp.csv
 
-          sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
-          if [[ $sp == 'false' ]]; then
-            echo Installing ${{ matrix.extensions }} extension...
-            if ! docker exec con $duckdb -c '$duckdb -c "INSTALL $ext;"'; then 
-              echo Failed to install ${{ matrix.extensions }} extension.
-              echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ matrix.extensions }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-              echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-              exit 1
+            sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
+            if [[ $sp == 'false' ]]; then
+              echo Installing $ext extension...
+              if ! docker run --rm --platform linux/aarch64 -v $(pwd)/duckdb:/duckdb -e ext=$ext -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c'$duckdb -c "INSTALL $ext;"'; then 
+                echo Failed to install $ext extension.
+                echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`$ext\` extension." >> issue_body_${{ inputs.architecture }}_$ext.txt
+                echo "" >> issue_body_${{ inputs.architecture }}_$ext.txt
+                exit 1
+              fi
+              echo Loading $ext extension...
+              if ! docker run --rm --platform linux/aarch64 -v $(pwd)/duckdb:/duckdb -e ext=$ext -e duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "LOAD $ext;"'; then
+                echo Failed to load $ext extension.
+                echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`$ext\`." >> issue_body_${{ inputs.architecture }}_$ext.txt
+                echo "" >> issue_body_${{ inputs.architecture }}_$ext.txt
+                exit 1
+              fi
             fi
-            echo Loading ${{ matrix.extensions }} extension...
-            if ! docker exec con $duckdb -c '$duckdb -c "LOAD $ext;"'; then
-              echo Failed to load ${{ matrix.extensions }} extension.
-              echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ matrix.extensions }}\`." >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-              echo "" >> issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
-              exit 1
-            fi
-          fi
+          done
 
       - name: Test ${{ inputs.nightly-build }}
         shell: bash
@@ -119,27 +125,28 @@ jobs:
           else
             duckdb=./duckdb
           fi
-          $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';"
-          $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ matrix.extensions }}';" > sp.csv
-          cat sp.csv
-          sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
-          if [[ $sp == 'false' ]]; then
-            echo Installing ${{ matrix.extensions }} extension...
-            if ! $duckdb -c "INSTALL ${{ inputs.extension }};"; then
-              echo Failed to install ${{ inputs.extension }} extension.
-              echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ inputs.extension }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-              echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-              exit 1
+          for ext in extensions; do
+            $duckdb -line -c "select installed from duckdb_extensions() where extension_name='$ext';"
+            $duckdb -line -c "select installed from duckdb_extensions() where extension_name='$ext';" > sp.csv
+            cat sp.csv
+            sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
+            if [[ $sp == 'false' ]]; then
+              echo Installing $ext extension...
+              if ! $duckdb -c "INSTALL ${{ inputs.extension }};"; then
+                echo Failed to install ${{ inputs.extension }} extension.
+                echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ inputs.extension }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+                echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+                exit 1
+              fi
+              echo Loading ${{ inputs.extension }} extension...
+              if ! $duckdb -c "LOAD ${{ inputs.extension }};"; then
+                echo Failed to load ${{ inputs.extension }} extension.
+                echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ inputs.extension }}\`." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+                echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+                exit 1
+              fi
             fi
-            echo Loading ${{ inputs.extension }} extension...
-            if ! $duckdb -c "LOAD ${{ inputs.extension }};"; then
-              echo Failed to load ${{ inputs.extension }} extension.
-              echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ inputs.extension }}\`." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-              echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-              exit 1
-            fi
-          fi
-      
+          done
       
       # - name: Setup upterm session
       #   uses: owenthereal/action-upterm@v1
@@ -148,5 +155,5 @@ jobs:
         uses: actions/upload-artifact@v4
         if: failure()
         with:
-          name: issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}
-          path: issue_body_${{ inputs.architecture }}_${{ matrix.extensions }}.txt
+          name: issue_body_${{ inputs.architecture }}_$ext
+          path: issue_body_${{ inputs.architecture }}_$ext.txt
