.github/workflows/tests_nbc_copy.yml

diff --git a/.github/workflows/tests_nbc_copy.yml b/.github/workflows/tests_nbc_copy.yml
--- a/.github/workflows/tests_nbc_copy.yml
+++ b/.github/workflows/tests_nbc_copy.yml
@@ -54,32 +54,32 @@ jobs:
             duckdb=./duckdb
           fi
 
-          docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ inputs.extension }} ubuntu:22.04 /bin/bash -c 'cd /duckdb; ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > pragma_version.csv
+          docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ inputs.extension }},duckdb=$duckdb ubuntu:22.04 /bin/bash -c 'cd /duckdb; ./duckdb -line -c "select installed from duckdb_extensions() where extension_name='\''${ext}'\'';"' > sp.csv
 
 
           # $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ inputs.extension }}';"
           # $duckdb -line -c "select installed from duckdb_extensions() where extension_name='${{ inputs.extension }}';" > sp.csv
           # sp=$(tail -n 1 sp.csv | awk '{ print $3 }')
-          # if [[ $sp == 'false' ]]; then
-          #   echo Installing ${{ inputs.extension }} extension...
-          #   if $duckdb -c "INSTALL ${{ inputs.extension }};"; then
-          #     echo ${{ inputs.extension }} extension is installed.
-          #   else
-          #     echo Failed to install ${{ inputs.extension }} extension.
-          #     echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ inputs.extension }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-          #     echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-          #     exit 1
-          #   fi
-          #   echo Loading ${{ inputs.extension }} extension...
-          #   if $duckdb -c "LOAD ${{ inputs.extension }};"; then
-          #     echo ${{ inputs.extension }} extension is loaded.
-          #   else
-          #     echo Failed to load ${{ inputs.extension }} extension.
-          #     echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ inputs.extension }}\`." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-          #     echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
-          #     exit 1
-          #   fi
-          # fi
+          if [[ $sp == 'false' ]]; then
+            echo Installing ${{ inputs.extension }} extension...
+            if docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ inputs.extension }},duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "INSTALL $ext;"'; then 
+              echo ${{ inputs.extension }} extension is installed.
+            else
+              echo Failed to install ${{ inputs.extension }} extension.
+              echo "- \`${{ inputs.architecture }}\`: **Failed** to install \`${{ inputs.extension }}\` extension." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              exit 1
+            fi
+            echo Loading ${{ inputs.extension }} extension...
+            if docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb -e ext=${{ inputs.extension }},duckdb=$duckdb ubuntu:22.04 /bin/bash -c '$duckdb -c "LOAD $ext;"'; then
+              echo ${{ inputs.extension }} extension is loaded.
+            else
+              echo Failed to load ${{ inputs.extension }} extension.
+              echo "- \`${{ inputs.architecture }}\`: **Failed** to load the extension \`${{ inputs.extension }}\`." >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              echo "" >> issue_body_${{ inputs.architecture }}_${{ inputs.extension }}.txt
+              exit 1
+            fi
+          fi
       
       # - name: Setup upterm session
       #   uses: owenthereal/action-upterm@v1
